import os
import re
import json
import argparse
import requests

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--deepseek_key", default="sk-f7bab04b152a41019eb8c360bcb3c177", type=str) 
    parser.add_argument("--prompt_file", default="collectdata/prompt_en.txt", help="The prompt file generated by build_llm_prompt.py")
    parser.add_argument("--out_file", default="collectdata/deepseek_result.txt", help="Where to save the raw model reply and parsed label")
    parser.add_argument("--model", default="deepseek-chat", help="DeepSeek model name")
    parser.add_argument("--temperature", type=float, default=0.2)
    parser.add_argument("--timeout", type=float, default=60.0, help="HTTP timeout (seconds)")
    args = parser.parse_args()

    # --- Read prompt ---
    if not os.path.isfile(args.prompt_file):
        raise FileNotFoundError(f"Prompt file not found: {args.prompt_file}")
    with open(args.prompt_file, "r", encoding="utf-8") as f:
        prompt_text = f.read().strip()
    if not prompt_text:
        raise ValueError("Prompt file is empty.")

    # --- API setup ---
    deepseek_api_url = "https://api.deepseek.com/v1/chat/completions"
    deepseek_headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {args.deepseek_key}",
    }
    temperature = args.temperature

    def call_deepseek_api(messages, model="deepseek-chat", temperature=1.0):
        """调用DeepSeek API"""
        data = {
            "model": model,
            "messages": messages,
            "temperature": temperature
        }
        try:
            resp = requests.post(
                deepseek_api_url,
                headers=deepseek_headers,
                json=data,
                timeout=args.timeout,
            )
            resp.raise_for_status()
            return resp.json()
        except requests.exceptions.RequestException as e:
            print(f"DeepSeek API调用失败: {e}")
            if hasattr(e, "response") and getattr(e, "response") is not None:
                try:
                    print("Response text:", e.response.text)
                except Exception:
                    pass
            raise

    messages = [
        {"role": "system", "content": "You are a precise classifier. Follow the format strictly."},
        {"role": "user", "content": prompt_text},
    ]

    result = call_deepseek_api(messages, model=args.model, temperature=temperature)

    raw_text = ""
    try:
        raw_text = result["choices"][0]["message"]["content"]
    except Exception:
        raw_text = json.dumps(result, ensure_ascii=False)
    parsed = raw_text.strip()

    # 只保留一个数字 1/2/3
    # 规则：取文本中的第一个独立的字符 1|2|3；若没有，回退到正则全局查找
    label = None
    m = re.search(r"\b([123])\b", parsed)
    if m:
        label = m.group(1)
    else:
        # 宽松回退：找第一个 '1'/'2'/'3'
        m2 = re.search(r"[123]", parsed)
        if m2:
            label = m2.group(0)

    # --- Print & Save ---
    os.makedirs(os.path.dirname(os.path.abspath(args.out_file)), exist_ok=True)
    with open(args.out_file, "w", encoding="utf-8") as f:
        f.write("# Raw reply from DeepSeek\n")
        f.write(raw_text + "\n\n")
        f.write("# Parsed label (should be 1/2/3)\n")
        f.write((label or "PARSE_FAILED") + "\n")

    print("==== DeepSeek raw reply ====")
    print(raw_text)
    print("==== Parsed label ====")
    print(label or "PARSE_FAILED")
    print(f"✅ Saved to: {os.path.abspath(args.out_file)}")

if __name__ == "__main__":
    main()
